package pojo;
// Generated Oct 1, 2024 1:24:34 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Menu generated by hbm2java
 */
public class Menu  implements java.io.Serializable {


     private Integer menuId;
     private String name;
     private String description;
     private BigDecimal price;
     private String category;
     private Boolean available;
     private Date createdAt;
     private Set orderses = new HashSet(0);

    public Menu() {
    }

	
    public Menu(String name, BigDecimal price, Date createdAt) {
        this.name = name;
        this.price = price;
        this.createdAt = createdAt;
    }
    public Menu(String name, String description, BigDecimal price, String category, Boolean available, Date createdAt, Set orderses) {
       this.name = name;
       this.description = description;
       this.price = price;
       this.category = category;
       this.available = available;
       this.createdAt = createdAt;
       this.orderses = orderses;
    }
   
    public Integer getMenuId() {
        return this.menuId;
    }
    
    public void setMenuId(Integer menuId) {
        this.menuId = menuId;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public BigDecimal getPrice() {
        return this.price;
    }
    
    public void setPrice(BigDecimal price) {
        this.price = price;
    }
    public String getCategory() {
        return this.category;
    }
    
    public void setCategory(String category) {
        this.category = category;
    }
    public Boolean getAvailable() {
        return this.available;
    }
    
    public void setAvailable(Boolean available) {
        this.available = available;
    }
    public Date getCreatedAt() {
        return this.createdAt;
    }
    
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }
    public Set getOrderses() {
        return this.orderses;
    }
    
    public void setOrderses(Set orderses) {
        this.orderses = orderses;
    }




}


