package pojo;
// Generated Oct 1, 2024 1:24:34 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * Payment generated by hbm2java
 */
public class Payment  implements java.io.Serializable {


     private Integer paymentId;
     private Orders orders;
     private String paymentMethod;
     private Date paymentDate;
     private BigDecimal amountPaid;

    public Payment() {
    }

	
    public Payment(String paymentMethod, Date paymentDate, BigDecimal amountPaid) {
        this.paymentMethod = paymentMethod;
        this.paymentDate = paymentDate;
        this.amountPaid = amountPaid;
    }
    public Payment(Orders orders, String paymentMethod, Date paymentDate, BigDecimal amountPaid) {
       this.orders = orders;
       this.paymentMethod = paymentMethod;
       this.paymentDate = paymentDate;
       this.amountPaid = amountPaid;
    }
   
    public Integer getPaymentId() {
        return this.paymentId;
    }
    
    public void setPaymentId(Integer paymentId) {
        this.paymentId = paymentId;
    }
    public Orders getOrders() {
        return this.orders;
    }
    
    public void setOrders(Orders orders) {
        this.orders = orders;
    }
    public String getPaymentMethod() {
        return this.paymentMethod;
    }
    
    public void setPaymentMethod(String paymentMethod) {
        this.paymentMethod = paymentMethod;
    }
    public Date getPaymentDate() {
        return this.paymentDate;
    }
    
    public void setPaymentDate(Date paymentDate) {
        this.paymentDate = paymentDate;
    }
    public BigDecimal getAmountPaid() {
        return this.amountPaid;
    }
    
    public void setAmountPaid(BigDecimal amountPaid) {
        this.amountPaid = amountPaid;
    }




}


