package pojo;
// Generated Oct 1, 2024 1:24:34 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Reservation generated by hbm2java
 */
public class Reservation  implements java.io.Serializable {


     private Integer reservationId;
     private Users users;
     private int tableNumber;
     private Date reservationDate;
     private Date reservationTime;
     private String status;
     private Date createdAt;

    public Reservation() {
    }

	
    public Reservation(int tableNumber, Date reservationDate, Date reservationTime, Date createdAt) {
        this.tableNumber = tableNumber;
        this.reservationDate = reservationDate;
        this.reservationTime = reservationTime;
        this.createdAt = createdAt;
    }
    public Reservation(Users users, int tableNumber, Date reservationDate, Date reservationTime, String status, Date createdAt) {
       this.users = users;
       this.tableNumber = tableNumber;
       this.reservationDate = reservationDate;
       this.reservationTime = reservationTime;
       this.status = status;
       this.createdAt = createdAt;
    }
   
    public Integer getReservationId() {
        return this.reservationId;
    }
    
    public void setReservationId(Integer reservationId) {
        this.reservationId = reservationId;
    }
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }
    public int getTableNumber() {
        return this.tableNumber;
    }
    
    public void setTableNumber(int tableNumber) {
        this.tableNumber = tableNumber;
    }
    public Date getReservationDate() {
        return this.reservationDate;
    }
    
    public void setReservationDate(Date reservationDate) {
        this.reservationDate = reservationDate;
    }
    public Date getReservationTime() {
        return this.reservationTime;
    }
    
    public void setReservationTime(Date reservationTime) {
        this.reservationTime = reservationTime;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public Date getCreatedAt() {
        return this.createdAt;
    }
    
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }




}


